### ISSUE TITLE
DataBase Design 

### ISSUE THREAD

**Issue by KotaSakurai** [KotaSakurai/shampers#1]
# テーブル設計の案 ver1.0
シャンプーについてのSNS,口コミサイトのようなもののテーブル設計案

![shampers-er 001](https://user-images.githubusercontent.com/28912034/28056428-df3505b2-6657-11e7-9c6b-108e674bccf6.jpeg)

## 基礎機能
- ユーザ認証
- シャンプー登録  
- シャンプーのレビュー

## 追加機能
- 買ったよ！数カウント
- 使ったことある！数カウント

## シャンプーレビューの中身
大幅な変更予定あり
- レビュー者
- コメント
- どこで買ったか
- 以前のシャンプーよりも良いか
- もう一度買いたいか

フィードバックがあるので、7/12に修正予定

**Comment by YasukeXXX** [comment]
性別は２値で表現できないと思います
http://www.ringo-bito.com/entry/iphone-facebook-gender

**Comment by kazumalab** [comment]
気になる点が３点あります。
- Shampoos -> UsedShampoosは複数持つと思われます。
- boughtshampoosはレビューを観て買ったよ！ということでしょうか？
- booleanの名前の付け方他に良いのありそうな気がします！(ひと目でBooleanだ！とわかるもの)

**Comment by KotaSakurai** [comment]
@YasukeXXX 
時代に追いついていませんでした。int型にしておき、必要に応じてgendersテーブルを用意しようかなと思います。

**Comment by KotaSakurai** [comment]
@kazumalab 
>Shampoos -> UsedShampoosは複数持つと思われます。

こちら、ミスでした。修正します。

>boughtshampoosはレビューを観て買ったよ！ということでしょうか？
そうですね、いいね！ボタンのような実装をしようと考えています。

>booleanの名前の付け方他に良いのありそうな気がします！(ひと目でBooleanだ！とわかるもの)
アドバイスありがとうございます。
経験不足を感じました。何かよい例を示す記事があれば紹介していただけるとうれしいです。

**Comment by KotaSakurai** [comment]
# テーブル設計の案 ver0.2

![shampers-er 001](https://user-images.githubusercontent.com/28912034/28096712-d2047394-66e5-11e7-9f36-ee9c3c94c1ee.jpeg)

## 機能について
UsedShampoosは、ユーザがシャンプーに対して使ったことがあれば、いいね！のように残すためのテーブルです。

BoughtShampoosは、ユーザが誰かのレビューに対して買った！！と残すためのテーブルです。

**Comment by KotaSakurai** [comment]
# テーブル設計の案 ver2.0
![shampers-er ver2 001](https://user-images.githubusercontent.com/28912034/28098437-323e6fe8-66f1-11e7-82cd-b9677d4df187.jpeg)

# 変更点
レビューの機能自体を見直して、instagramのタグ(#)で１つのシャンプーに対して色々と情報を付与するものにしようと思います。

## シャンプーにつけられる情報
- タグ
- 買った場所
- コメント
- 前のシャンプーよりよかったか

を投稿できるようにしようと思います。

**Comment by kiyokuro** [comment]
２つ質問です。
* Shampoosには画像は１枚しか登録できない仕様ですか？１つのシャンプーに対して１つの写真？
* tagsにはuser_idを持たせているのは、タグを登録したユーザーを知るためとかですか？

**Comment by KotaSakurai** [comment]
@kiyokuro 
> Shampoosには画像は１枚しか登録できない仕様ですか？１つのシャンプーに対して１つの写真？

現在はShampoosに１枚の画像のみを登録させようと思っています。
シャンプーに対してどう思っているか、といった情報を集めることにフォーカスしているため、シャンプーがどう見えるかの部分は１枚の画像で満たせると考えているからです。
画像を追加する場合は、画像用のテーブルを作成し、Shampoosにタグ付けのような感覚で投稿できるようにしようと思います。

> tagsにはuser_idを持たせているのは、タグを登録したユーザーを知るためとかですか？

はい、そうです。
